version: "3"
services:
  decodes-api:
    image: trevorsharp/decodes-api
    container_name: decodes-api
    expose:
      - "3000"
    environment:
      - "MONGODB_SERVER=decodes-mongodb"
      - "MONGODB_DATABASE=decodes1"
      - "FRONTEND_URL=https://decodes.stream"
  decodes-nginx:
    image: trevorsharp/decodes-nginx
    container_name: decodes-nginx
    ports:
      - 443:443
    volumes:
      - ./ssl:/ssl
      - ./hosts:/hosts
  decodes-mongodb:
    image: mongo
    container_name: decodes-mongodb
    volumes:
      - /database:/data/db
    expose:
      - "27017"
    restart: unless-stopped
  decodes-mongodb-ui:
    image: mongo-express
    container_name: decodes-mongodb-ui
    expose:
      - "8081"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=decodes-mongodb"
      - "ME_CONFIG_BASICAUTH_USERNAME=sharp"
      - "ME_CONFIG_BASICAUTH_PASSWORD=password"
      - "ME_CONFIG_SITE_BASEURL=/manage/"
