FROM node:14.16.0-alpine

RUN apk add --no-cache yarn

WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
RUN yarn

COPY ./src ./src
COPY ./tsconfig.json ./tsconfig.json
RUN yarn build

CMD node /app/build/index.js